export const SITE_CONFIG = {
  name: 'Uganda Sexy Babes',
  tagline: "Uganda's #1 Dating & Companionship Directory",
  description:
    'Browse Uganda Sexy Babes — the top dating and companionship site for meeting beautiful, verified babes in Kampala, Entebbe, Jinja and across Uganda. Direct WhatsApp and phone contact.',
  url: process.env.NEXT_PUBLIC_SITE_URL || 'https://ugandasexybabes.afrozex.com',
  keywords: [
    'uganda escorts',
    'ug escorts',
    'escorts',
    'escorts ug',
    'escorts uganda',
    'uganda hot girls',
    'hot girls',
    'sexy girls',
    'sexy babes',
    'hot babes',
    'massage and hook up',
    'verified escorts',
    'verified escorts in uganda',
    'escorts in uganda',
    'escorts in ug',
    'kampala hot girls',
    'kampala escorts',
    'sexy escorts',
    'sexy escorts in uganda',
    'hookup girls',
    'hookup girls in uganda',
    'verified hookups in uganda',
    'ntinda escorts',
    'kasubi escorts',
    'escorts around kampala',
    'kisaasi escorts',
    'kololo escorts',
    'entebbe escorts',
    'kawempe escorts',
    'sweet girls',
    'sweet escorts',
    'affordable escorts',
    'makindye escorts',
    'escorts in kampala',
    'escorts in town',
    'escorts in kampala town',
    'call girls',
    'uganda girls',
    'erotic girls',
    'ebony girls',
    'ebony sexy babes',
    'ebony sexy girls',
    'sweet ebony girls',
    'ebony kampala',
    'adult entertainment',
    'afrohot',
    'afro girls',
    'afrohot girls',
    'uganda hot babes',
    'delivery girls',
    'sugar mummies',
    'sugar mummies in uganda',
    'hot sugar mummies',
    'escort apps ug',
    'escorts site ug',
    'escorts sites in uganda',
    'top escorts sites in uganda',
    'legit escort girls',
    'legit escorts in uganda',
    'hookup calls ug',
    'verified hookup calls ug',
    'hostess escorts',
    'uganda divas',
    'companionship girls',
    'massage',
    'spas',
    'legit spas',
    'massage spas',
    'legit massage spas',
    'massage spas in ug',
    'legit spas in uganda',
    'uganda massage spas',
    'premium escorts',
    'premium escorts in uganda',
    'premier connect ug',
    'independent escorts',
    'discreet escorts',
    'kampala uganda',
    'escorthub',
    'escorts hub',
    'kampala hot',
    'kampala hot escorts',
    'uganda escorts list',
    'uganda escort list',
    'escort girls agencies',
    'hot sexy ugandan escorts',
    'sexy hook ups in uganda',
    'sexy hookups in kampala',
    'all escorts',
    'top sweet girls',
    'ugandan girls',
    'night girls',
    'night shift',
    'escorts and massage',
    'full package massage',
    'uganda hot life',
    'bed escorts',
    'happiness in bed',
    'pearl escorts',
    'escort news',
    'munyonyo escorts',
    'muyenga escorts',
    'uganda hot',
    'top escorts',
    'top escorts in africa',
    'top escorts in uganda',
    'top escorts in kampala',
    'vip escorts',
    'vip escorts ug',
    'vip escorts in uganda',
    'escort women',
    'escort girls',
    'exotic escorts',
    'shy girls',
    'dubai escorts',
    'kikoni sure',
    'dating',
    'girls to date',
    'female escorts',
    'pure escorts',
    'escorts services',
    'massage escorts',
    'massage girls',
    'massage and escorts',
    'kampala female escorts',
    'pure kampala girls',
    'pure escort ug',
    'best escorts',
    'best uganda sites in uganda',
    'best escorts ug',
  ],
  defaultOgImage: '/logo.png',
};

export function getBaseUrl(): string {
  if (process.env.NEXT_PUBLIC_SITE_URL) {
    return process.env.NEXT_PUBLIC_SITE_URL.replace(/\/$/, '');
  }
  return 'https://ugandasexybabes.afrozex.com';
}
