export const SITE_CONFIG = {
  name: 'Uganda Sexy Babes',
  tagline: "Uganda's #1 Adult Hookup, Escort & Dating Platform",
  description:
    'Uganda Sexy Babes — the #1 adult platform for hookups, dating, casual encounters, and verified escort companions in Kampala, Entebbe, Jinja, Mbarara and across Uganda. Real girls, direct WhatsApp contact. Discreet, fast, 18+.',
  url: process.env.NEXT_PUBLIC_SITE_URL || 'https://ugandasexybabes.afrozex.com',
  keywords: [
    // ── Core Directory Terms ──────────────────────────────────────────────────
    'uganda escorts',
    'ug escorts',
    'escorts',
    'escorts ug',
    'escorts uganda',
    'verified escorts',
    'verified escorts in uganda',
    'escorts in uganda',
    'escorts in ug',
    'legit escort girls',
    'legit escorts in uganda',
    'independent escorts',
    'discreet escorts',
    'premium escorts',
    'premium escorts in uganda',
    'vip escorts',
    'vip escorts ug',
    'vip escorts in uganda',
    'affordable escorts',
    'female escorts',
    'escort women',
    'escort girls',
    'exotic escorts',
    'escort girls agencies',
    'all escorts',
    'escort apps ug',
    'escorts site ug',
    'escorts sites in uganda',
    'top escorts sites in uganda',
    'best escorts',
    'best escorts ug',
    'uganda escorts list',
    'uganda escort list',
    'pure escorts',
    'pure escort ug',
    'escorts services',
    'escorthub',
    'escorts hub',
    'pearl escorts',
    'bed escorts',
    'hostess escorts',
    // ── Kampala & Suburbs ─────────────────────────────────────────────────────
    'kampala escorts',
    'kampala hot girls',
    'kampala hot escorts',
    'kampala hot',
    'kampala female escorts',
    'pure kampala girls',
    'kampala uganda',
    'escorts in kampala',
    'escorts in town',
    'escorts in kampala town',
    'escorts around kampala',
    'top escorts in kampala',
    'sexy hookups in kampala',
    'ntinda escorts',
    'kasubi escorts',
    'kisaasi escorts',
    'kololo escorts',
    'kawempe escorts',
    'makindye escorts',
    'munyonyo escorts',
    'muyenga escorts',
    'entebbe escorts',
    'kikoni sure',
    // ── Dating & Hookup ───────────────────────────────────────────────────────
    'hookup',
    'hookup uganda',
    'hookup girls',
    'hookup girls in uganda',
    'hookup girls kampala',
    'hookup girls uganda',
    'hookup calls ug',
    'verified hookup calls ug',
    'verified hookups in uganda',
    'hookup site uganda',
    'hookup app uganda',
    'casual hookup kampala',
    'casual encounters uganda',
    'meet and mingle uganda',
    'no strings attached uganda',
    'one night stand uganda',
    'quick hookup kampala',
    'local hookups uganda',
    'sexy hook ups in uganda',
    'dating',
    'adult dating uganda',
    'girls to date',
    // ── Girls & Babes ─────────────────────────────────────────────────────────
    'uganda hot girls',
    'hot girls',
    'sexy girls',
    'sexy babes',
    'hot babes',
    'uganda hot babes',
    'sweet girls',
    'sweet escorts',
    'ugandan girls',
    'uganda girls',
    'ebony girls',
    'ebony sexy babes',
    'ebony sexy girls',
    'sweet ebony girls',
    'ebony kampala',
    'afro girls',
    'afrohot girls',
    'afrohot',
    'top sweet girls',
    'shy girls',
    'night girls',
    'delivery girls',
    'companionship girls',
    'uganda divas',
    'call girls',
    'sexy escorts',
    'sexy escorts in uganda',
    'hot sexy ugandan escorts',
    'exotic escorts',
    // ── Massage & Services ────────────────────────────────────────────────────
    'massage',
    'massage and hook up',
    'massage spas',
    'massage spas in ug',
    'legit spas',
    'legit spas in uganda',
    'legit massage spas',
    'uganda massage spas',
    'spas',
    'massage escorts',
    'massage girls',
    'massage and escorts',
    'escorts and massage',
    'full package massage',
    // ── Sugar Mummies & Companions ────────────────────────────────────────────
    'sugar mummies',
    'sugar mummies in uganda',
    'hot sugar mummies',
    // ── Platform & Discovery ──────────────────────────────────────────────────
    'top escorts',
    'top escorts in africa',
    'top escorts in uganda',
    'adult entertainment',
    'adult entertainment kampala',
    'adult hookup site uganda',
    'adult dating uganda',
    'premier connect ug',
    'uganda hot',
    'uganda hot life',
    'happiness in bed',
    'escort news',
    'night shift',
    'dubai escorts',
    'best uganda sites in uganda',
    'nsa hookup uganda',
  ],
  defaultOgImage: '/logo.png',
};

export function getBaseUrl(): string {
  if (process.env.NEXT_PUBLIC_SITE_URL) {
    return process.env.NEXT_PUBLIC_SITE_URL.replace(/\/$/, '');
  }
  return 'https://ugandasexybabes.afrozex.com';
}
